#port 결정 default 8080 -> 9090
spring:
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver

  thymeleaf: 
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML

mybatis: 
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
  
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE